//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotyHitss.UI.Client.SpotyHitssProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpotyHitssProxy.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSearchGenListSong", ReplyAction="http://tempuri.org/IService1/GetSearchGenListSongResponse")]
        SpotyHitss.Data.Objects.Song[] GetSearchGenListSong(string Genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSearchGenListSong", ReplyAction="http://tempuri.org/IService1/GetSearchGenListSongResponse")]
        System.Threading.Tasks.Task<SpotyHitss.Data.Objects.Song[]> GetSearchGenListSongAsync(string Genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListSongContract", ReplyAction="http://tempuri.org/IService1/GetListSongContractResponse")]
        SpotyHitss.Data.Objects.SongArtist[] GetListSongContract(string Artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetListSongContract", ReplyAction="http://tempuri.org/IService1/GetListSongContractResponse")]
        System.Threading.Tasks.Task<SpotyHitss.Data.Objects.SongArtist[]> GetListSongContractAsync(string Artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAlbum", ReplyAction="http://tempuri.org/IService1/AddAlbumResponse")]
        string AddAlbum(int ReleaseYear, string Album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAlbum", ReplyAction="http://tempuri.org/IService1/AddAlbumResponse")]
        System.Threading.Tasks.Task<string> AddAlbumAsync(int ReleaseYear, string Album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSong", ReplyAction="http://tempuri.org/IService1/InsertSongResponse")]
        SpotyHitss.Data.Objects.OperationResult<int> InsertSong(string name, string artistName, int year, byte[] songData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertSong", ReplyAction="http://tempuri.org/IService1/InsertSongResponse")]
        System.Threading.Tasks.Task<SpotyHitss.Data.Objects.OperationResult<int>> InsertSongAsync(string name, string artistName, int year, byte[] songData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SpotyHitss.UI.Client.SpotyHitssProxy.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SpotyHitss.UI.Client.SpotyHitssProxy.IService1>, SpotyHitss.UI.Client.SpotyHitssProxy.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SpotyHitss.Data.Objects.Song[] GetSearchGenListSong(string Genre) {
            return base.Channel.GetSearchGenListSong(Genre);
        }
        
        public System.Threading.Tasks.Task<SpotyHitss.Data.Objects.Song[]> GetSearchGenListSongAsync(string Genre) {
            return base.Channel.GetSearchGenListSongAsync(Genre);
        }
        
        public SpotyHitss.Data.Objects.SongArtist[] GetListSongContract(string Artist) {
            return base.Channel.GetListSongContract(Artist);
        }
        
        public System.Threading.Tasks.Task<SpotyHitss.Data.Objects.SongArtist[]> GetListSongContractAsync(string Artist) {
            return base.Channel.GetListSongContractAsync(Artist);
        }
        
        public string AddAlbum(int ReleaseYear, string Album) {
            return base.Channel.AddAlbum(ReleaseYear, Album);
        }
        
        public System.Threading.Tasks.Task<string> AddAlbumAsync(int ReleaseYear, string Album) {
            return base.Channel.AddAlbumAsync(ReleaseYear, Album);
        }
        
        public SpotyHitss.Data.Objects.OperationResult<int> InsertSong(string name, string artistName, int year, byte[] songData) {
            return base.Channel.InsertSong(name, artistName, year, songData);
        }
        
        public System.Threading.Tasks.Task<SpotyHitss.Data.Objects.OperationResult<int>> InsertSongAsync(string name, string artistName, int year, byte[] songData) {
            return base.Channel.InsertSongAsync(name, artistName, year, songData);
        }
    }
}
